version: "3"
services:
  uwsgi:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - .:/var/www/django/codes
  nginx:
    ports:
      - 80:80
    build: ./nginx
    depends_on :
      - uwsgi
    volumes:
      - ./nginx/nginx-app.conf:/etc/nginx/nginx.conf
      - static_volume:/var/www/django/code/staticfiles