# Generated by Django 5.0.4 on 2024-08-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=10)),
                ("logo", models.ImageField(null=True, upload_to="team_logos/")),
                (
                    "initial_logo",
                    models.ImageField(null=True, upload_to="team_initial_logos/"),
                ),
            ],
        ),
    ]
