# Generated by Django 5.0.4 on 2024-08-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kbo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="initial_logo",
            field=models.ImageField(null=True, upload_to="static/team_initial_logos/"),
        ),
        migrations.AddField(
            model_name="team",
            name="logo",
            field=models.ImageField(null=True, upload_to="static/team_logos/"),
        ),
    ]
