# Generated by Django 5.0.4 on 2024-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="memo",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
